### ISSUE TITLE
Bar graphs

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/seagrasstransect#2]
@fawda123 I'm going to go back in to the data and do a better job of randomization for demonstration. Can't remember if asked about this before, please do bar graphs, with segment/transect on horizontal and parameter (abundance, root count, or shoot count) on vertical, similar to this:
https://drive.google.com/open?id=1ssHZA5ZX9zao2KTNDFlBpwdzB5pE8TyX 
Thanks,
Gman

**Comment by fawda123** [comment]
Done 570f17c37b0972c985bf60adcb208eeb718e024f
